//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nagarro.BookReadingEvent.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment1
    {
        public int Id { get; set; }
        public string Comment11 { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Username { get; set; }
        public Nullable<int> EventId { get; set; }
    
        public virtual Event1 Event { get; set; }
    }
}
